config/routes.rb
# Rails Bootstrap
# @author Tiago <tiago@tamworks.com>

RailsBootstrap::Application.routes.draw do

  devise_for :users, :path_prefix => 'auth'

  authenticated :user do
    root :to => 'reports#dashboard', as: :authenticated_root
  end
  unauthenticated do
    root :to => 'pages#index'
  end


  # Páginas Públicas
  get 'terms', to: 'pages#terms'


  # Relatórios
  get 'dashboard', to: 'reports#dashboard'

  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end
  resources :companies

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  match "*path", :to => "application#routing_error", :via => :all

end

app/models/user.rb
# Rails Bootstrap
# @author Tiago <tiago@tamworks.com>
# -*- coding: utf-8 -*-

class User < ActiveRecord::Base

  #-------------------
  # Extentions
  #-------------------
  extend FriendlyId
  friendly_id :uuid

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  #-------------------
  # Associations
  #-------------------
  belongs_to :company


  #-------------------
  # Accessors
  #-------------------
  attr_accessor :company_name
  attr_accessor :send_password

  #-------------------
  # Validations
  #-------------------
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :company_name, :presence => true, :if => :should_validate_company

  #-------------------
  # Scopes
  #-------------------
  default_scope {order(full_name: :asc)}

  #-------------------
  # Callbacks
  #-------------------
  before_create :set_fields
  before_save :update_full_name
  after_create :send_welcome_email


  #-------------------
  # Public Methods
  #-------------------


  def should_validate_company
    !self.persisted? and self.company.nil?
  end

  def send_welcome_email
    UserMailer.welcome(self).deliver
  end


  #-------------------
  # Private Methods
  #-------------------

  private

  def update_full_name
    self.full_name = "#{self.first_name} #{self.last_name}"
  end

  def set_fields
    self.uuid = SecureRandom.uuid
    if self.company_name.present? && self.company.nil?
      self.company = Company.create(:name => company_name)
    end
  end


end

app/controllers/users_controller.rb
# Rails Bootstrap
# @author Tiago <tiago@tamworks.com>
# -*- coding: utf-8 -*-

class UsersController < ApplicationController
    
  before_filter :authenticate_user!

  # Action for create a new user
  def new
    @user = User.new
  end

  # Action for persist a new user
  def create
    @user = User.create(user_params_with_password)
    @user.company = current_user.company
    if @user.save
      flash[:success] = t('messages.default_success')
      redirect_to users_path
    else
      render :new
    end
  end

  # Action for edit a new user
  def edit
    if params[:id].present?
      @user = User.find_by_uuid(params[:id])
    else
      @user = current_user
    end
  end

  # Action for edit password of specific user passed by parameter
  def edit_password
    if params[:id].present?
      @user = User.find_by_uuid(params[:id])
    end
  end

  # Action for change and persist the new password
  # It will also notify the user, based on flag 'send_password' submitted by the user
  def update_password
    @user = User.find_by_uuid(params[:id])
    if @user.update(user_params_with_password)
      if @user.send_password.present? && @user.send_password.to_i == 1
        @user.send_welcome_email
      end
      flash[:success] = t('messages.default_success')
      redirect_to users_path
    else
      flash[:error] = t('messages.default_error')
      render :edit_password
    end
  end

  # Action for persist the changes in specific user
  def update
    @user = User.find_by_uuid(params[:id])
    if @user.update(user_params_without_password)
      flash[:success] = t('messages.default_success')
      redirect_to users_path
    else
      flash[:error] = t('messages.default_error')
      render :edit
    end
  end

  # Action for show user details
  def show
    if params[:id].present?
      @user = User.find_by_uuid(params[:id])
    else
      @user = current_user
    end
  end

  # Action for delete specific user
  def destroy
    @user = User.find_by_uuid(params[:id])
    if @user.destroy
      flash[:success] = t('messages.default_success')
    else
      flash[:error] = t('messages.default_error')
    end
    redirect_to users_path
  end

  # Action for list all users from current company
  def index
    params[:q] = {} if params[:q].blank?
    params[:q][:company_id_eq] = current_user.company_id
    @q = User.search(params[:q])
    @users = @q.result(:distinct => true).paginate(:page => params[:page])
  end

  private

  # Sanitize form parameters without password
  def user_params_without_password
    params.required(:user).permit(:first_name, :last_name, :email)
  end

  # Sanitize form parameters will all allowed fields for model user
  def user_params_with_password
    params.required(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :send_password)
  end
  
end

app/views/users/_filter.html.erb
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#filter">
          <i class="icon-filter"></i>
          <%= t('filter')%>
        </a>
      </h4>
    </div>
    <div id="filter" class="panel-collapse collapse in">
      <div class="panel-body">
        <%= search_form_for @q do |f| %>
          <table class="table">
            <colgroup>
              <col width="15%"/>
              <col width="35%"/>
              <col width="15%"/>
              <col width="35%"/>
            </colgroup>
            <tr>
              <td class="right"><%= f.label :first_name_cont, t('activerecord.attributes.user.first_name') %>&nbsp;</td>
              <td><%= f.text_field :first_name_cont, class: 'form-control'  %></td>
              <td class="right"><%= f.label :last_name_cont, t('activerecord.attributes.user.last_name') %>&nbsp;</td>
              <td><%= f.text_field :last_name_cont, class: 'form-control'  %></td>
            </tr>
            <tr>
              <td class="right"><%= f.label :email_cont, t('activerecord.attributes.user.email') %>&nbsp;</td>
              <td><%= f.text_field :email_cont, class: 'form-control'  %></td>
              <td></td>
              <td></td>
            </tr>
          </table>
          <div class="center">
            <%= f.submit t('search'), :class => 'btn btn-default' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to t('home'), root_path %>
    </li>
    <li>
      <%= link_to t('users'), users_path %>
    </li>
    <li class="active"><%= t('edit_user')%></li>
  </ul>
  <!-- .breadcrumb -->
</div>


<%= add_page_title(t('edit') + " " + @user.full_name)%>

<div>
  <%= form_for(@user, html: {class: 'form-horizontal', role: 'form'}) do |f| %>
    <%= error_messages!(@user) %>
    <%= add_text_field(f, @user, :first_name)%>
    <%= add_text_field(f, @user, :last_name)%>
    <%= add_text_field(f, @user, :email)%>


    <% extra_buttons = [] %>
    <% extra_buttons << link_to(t('update_password'), edit_password_user_path(@user), class: 'btn btn-danger') %>
    <% extra_buttons << back %>

    <%= add_submit_button(f, t('save'), extra_buttons)%>

  <% end %>
</div>

app/views/users/edit_password.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to t('home'), root_path %>
    </li>
    <li>
      <%= link_to t('users'), users_path %>
    </li>
    <li class="active"><%= t('update_password')%></li>
  </ul>
  <!-- .breadcrumb -->
</div>

<%= add_page_title(t('update_password') + " de " + @user.full_name)%>

<div class="page-content">

  <%= form_for(@user, url: update_password_user_path(@user),html: {class: 'form-horizontal', role: 'form'}) do |f| %>

    <%= error_messages!(@user) %>
    <%= add_password_field(f, @user, :password, true)%>
    <%= add_password_field(f, @user, :password_confirmation, true)%>
    <%= add_checkbox_field(f, @user, :send_password, t('activerecord.attributes.user.send_password'), true) %>
    <%= add_submit_and_back_button(f) %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= add_page_title(t('users'))%>


<%= render partial: 'filter' %>


  <% if @users.any?%>

    <div class="digg_pagination">
      <div clas="page_info">
        <%= page_entries_info @users %>
      </div>
    </div>

    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th><%= t('activerecord.attributes.user.name')%></th>
            <th><%= t('activerecord.attributes.user.email')%></th>
            <th class="center"><%= t('actions')%></th>
          </tr>
        </thead>
        <tbody>
      <% @users.each do |user|%>
        <tr>
          <td><%=user.full_name %></td>
          <td><%=user.email%></td>

          <td>
            <div class="action-buttons">

              <a href="<%= user_path(user)%>">
                <i class="fa fa-search"></i>
              </a>

              &nbsp;&nbsp;

              <a href="<%= edit_user_path(user)%>">
                <i class="fa fa-pencil"></i>
              </a>

              &nbsp;&nbsp;

              <a href="<%= user_path(user)%>" data-method="delete"
                 data-confirm="<%= t('messages.confirm_before_delete')%>">
                  <i class="fa fa-trash-o"></i>
              </a>

            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
      </table>
    </div>
    <div class="digg_pagination">
      <%= will_paginate @companies, :container => false %>
    </div>

  <% end %>

  <div class="center form-actions">
    <%= link_to t('new_user'), new_user_path, class: 'btn btn-danger' %>
    &nbsp; &nbsp; &nbsp;
    <%= back %>
  </div>
</div>

app/views/users/new.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to t('home'), root_path %>
    </li>
    <li>
      <%= link_to t('users'), users_path %>
    </li>
    <li class="active"><%= t('new_user')%></li>
  </ul>
  <!-- .breadcrumb -->
</div>


<%= add_page_title(t('new_user') )%>

<div>
  <%= form_for(@user, html: {class: 'form-horizontal', role: 'form'}) do |f| %>

    <%= error_messages!(@user) %>
    <%= add_text_field(f, @user, :first_name)%>
    <%= add_text_field(f, @user, :last_name)%>
    <%= add_text_field(f, @user, :email)%>
    <%= add_password_field(f, @user, :password, true)%>
    <%= add_password_field(f, @user, :password_confirmation, true)%>
    <%= add_checkbox_field(f, @user, :send_password, t('activerecord.attributes.user.send_password'), true) %>
    <%= add_submit_and_back_button(f) %>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to t('home'), root_path %>
    </li>
    <li>
      <%= link_to t('users'), users_path %>
    </li>
    <li class="active"><%= @user.full_name %></li>
  </ul>
  <!-- .breadcrumb -->
</div>

<%= add_page_title(t(@user.full_name))%>



<div class="table-responsive">
  <table class="table">
    <colgroup>
      <col width="30%"/>
      <col width="70%"/>
    </colgroup>
    <tr>
      <th class="blue right"><%= t('activerecord.attributes.user.name')%></th>
      <td><%= @user.full_name%></td>
    </tr>
    <tr>
      <th class="blue right"><%= t('activerecord.attributes.user.email')%></th>
      <td><%= @user.email%></td>
    </tr>
    <tr>
      <th class="blue right"><%= t('company')%></th>
      <td><%= @user.company.name if @user.company.present? %></td>
    </tr>

    <tr>
      <th class="blue right"><%= t('activerecord.attributes.user.current_sign_in_at')%></th>
      <td><%= format_date_time(@user.last_sign_in_at) %></td>
    </tr>
    <tr>
      <th class="blue right"><%= t('activerecord.attributes.user.created_at')%></th>
      <td><%= format_date_time(@user.created_at) %></td>
    </tr>
  </table>
</div>


<div class="form-actions">
    <%= link_to t('edit_user'), edit_user_path(@user), class: 'btn btn-danger' %>
    &nbsp; &nbsp; &nbsp;
    <%= back %>
</div>