config/routes.rb
# Rails Bootstrap
# @author Tiago <tiago@tamworks.com>

RailsBootstrap::Application.routes.draw do

  devise_for :users, :path_prefix => 'auth'

  authenticated :user do
    root :to => 'reports#dashboard', as: :authenticated_root
  end
  unauthenticated do
    root :to => 'pages#index'
  end


  # Páginas Públicas
  get 'terms', to: 'pages#terms'


  # Relatórios
  get 'dashboard', to: 'reports#dashboard'

  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end
  resources :companies

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  match "*path", :to => "application#routing_error", :via => :all

end

app/views/pages/index.html.erb
<div class="jumbotron">
  <div class="container">

    <h1> Hello, world!</h1>
    <p>This is a template for quick start new project in rails using Bootstrap. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <a href="<%= new_registration_path(:user)%>" style="width:200px"
       class="btn btn-lg btn-success" title="Experimente!"><i class="icon-gift"></i> Cadastre-se Agora! »
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
  </div>
  <div class="col-md-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
  </div>
  <div class="col-md-4">
    <h2>Heading</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
    <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
  </div>
</div>

app/views/pages/terms.html.erb
<%= add_page_title(t('terms_of_usage'))%>

<div class="row">
  <div class="col-md-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  </div>
  <div class="col-md-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  </div>
  <div class="col-md-4">
    <h2>Heading</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
  </div>
</div>