config/routes.rb
# Rails Bootstrap
# @author Tiago <tiago@tamworks.com>

RailsBootstrap::Application.routes.draw do

  devise_for :users, :path_prefix => 'auth'

  authenticated :user do
    root :to => 'reports#dashboard', as: :authenticated_root
  end
  unauthenticated do
    root :to => 'pages#index'
  end


  # Páginas Públicas
  get 'terms', to: 'pages#terms'


  # Relatórios
  get 'dashboard', to: 'reports#dashboard'

  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end
  resources :companies

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  match "*path", :to => "application#routing_error", :via => :all

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale.to_s %>">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : APPLICATION_NAME %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <!--[if IE 7]>
        <%= stylesheet_link_tag "ie_lt7", media: "all", "data-turbolinks-track" => true %>
    <![endif]-->

  <!--[if lte IE 8]>
        <%= stylesheet_link_tag    "ie_lt8", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "ie_lt8", "data-turbolinks-track" => true %>
    <![endif]-->

  <!--[if lt IE 9]>
        <%= javascript_include_tag "ie_lt9", "data-turbolinks-track" => true %>
    <![endif]-->

  <%= csrf_meta_tags %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
</head>
<body role="document">

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to APPLICATION_NAME, root_path, :class => 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>

      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.full_name %>
            <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if current_user.company.present? %>
              <li>
                <%= link_to t('edit_my_company'), edit_company_path(current_user.company) %>
              </li>
            <% end %>
            <li>
              <%= link_to t('edit_my_user'), edit_user_registration_path %>
            </li>
            <li class="divider"></li>
            <li><%= link_to  t('sign_out'), destroy_user_session_path, {:method => :delete} %></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container-fluid">

  <div class="row">

    <div class="col-sm-3 col-md-2 sidebar">

      <div class="list-group">
        <%= link_to t('dashboard'), dashboard_path, :class => sidebar_get_class('reports', 'dashboard') %>
        <%= link_to t('users'), users_path, :class => sidebar_get_class('users') %>
        <a href="#" class="list-group-item">Link</a>
        <a href="#" class="list-group-item">Link</a>
      </div>

    </div>


    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>


  <%= render 'shared/footer' %>
</div>
</body>
</html>

app/views/layouts/email.html.erb
<div bgcolor="#e5e9ec">
  <div class="adM"></div>
  <table cellspacing="0" border="0" height="100%" bgcolor="#e5e9ec" cellpadding="0" width="100%">
    <tbody>
    <tr>
      <td align="center" valign="top">
        <table cellspacing="0" cellpadding="0" width="500">
          <tbody>
          <tr>
            <td align="left" height="6" colspan="2" bgcolor="#e5e9ec"></td>
          </tr>
          </tbody>
        </table>
        <table cellspacing="0" cellpadding="0" width="500" style="background:#fff" bgcolor="#ffffff">
          <tbody>
          <tr>
            <td align="center" valign="center" colspan="2" style="text-align:center;">

              <a href="<%= APPLICATION_BASE_URL %>" target="_blank">
                <h1><%= APPLICATION_NAME %></h1>
              </a>
            </td>
          </tr>
          <tr>
            <td valign="top" colspan="2" style="padding:10px">
              <%= yield :body %>
            </td>
          </tr>
          <tr>
            <td align="left" height="6" colspan="2" bgcolor="#e5e9ec">
            </td>
          </tr>
          </tbody>
        </table>
        <table width="500">
          <tbody>
          <tr>
            <td height="30" align="center">
              <font color="#777" face="Helvetica Neue, Arial, Helvetica, sans-serif" style="font-size:12px;line-height:1.5">
               <br><%= APPLICATION_NAME %>
              </font>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
    </tr>
    </tbody>
  </table>
</div>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Error</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>

    <%= javascript_include_tag 'application' %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
  </head>
  <body style="background-color: white;">

    <div class="container-fluid" style="text-align: center;">

      <%= image_tag 'error/csstricks.jpg' %>
      <br><br><br>

      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale.to_s %>">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : APPLICATION_NAME %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <!--[if IE 7]>
        <%= stylesheet_link_tag "ie_lt7", media: "all", "data-turbolinks-track" => true %>
    <![endif]-->

  <!--[if lte IE 8]>
        <%= stylesheet_link_tag    "ie_lt8", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "ie_lt8", "data-turbolinks-track" => true %>
    <![endif]-->

  <!--[if lt IE 9]>
        <%= javascript_include_tag "ie_lt9", "data-turbolinks-track" => true %>
    <![endif]-->

  <%= csrf_meta_tags %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
</head>
<body role="document">

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to APPLICATION_NAME, root_path, :class => 'navbar-brand' %>
    </div>
    <% if !['sessions', 'passwords'].include?(controller_name) %>
      <div class="navbar-collapse collapse">
        <%= form_for(resource, :as => resource_name,
        :url => session_path(resource_name),
        :html => {:class => 'navbar-form navbar-right'}, :role => 'form') do |f| %>

          <div class="form-group">
            <%= f.email_field :email, :placeholder => t('activerecord.attributes.user.email'), :class => 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.password_field :password, :placeholder => t('activerecord.attributes.user.password'), :class => 'form-control'%>
          </div>
          <%= f.submit(t('sign_in'), :class => 'btn btn-success')%>
          <%= link_to t('forgot_your_password'), new_password_path(resource_name) , :class => 'btn btn-danger'%>
        <% end %>
      </div><!--/.navbar-collapse -->
    <% end %>
  </div>
</div>


<div class="container">

  <%= bootstrap_flash %>
  <%= yield %>


  <%= render 'shared/footer' %>
</div>

</body>
</html>